import type { Metadata } from 'next'
import { spoqa } from '@/styles/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={`${spoqa.variable} font-spoqa`}>{children}</body>
    </html>
  )
}
